name: Mailboxes
version: 0.0
author: RandomPersson
main: net.nDARQ.RandomPersson.Mailboxes.Mailboxes2
commands:
  mailbox:
    description: Open your mailbox!
    aliases: [mb, mailboxes]
    permission: mailboxes.use